import Image from "next/image";
import type { Metadata } from "next";
import { ArrowRightIcon } from "@radix-ui/react-icons";
import { AppNav } from "@/components/AppNav";
import { BenchmarkReportSignup } from "@/components/BenchmarkReportSignup";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { BreadcrumbListJsonLd } from "@/components/BreadcrumbListJsonLd";
import { OutboundLink } from "@/components/OutboundLink";
import { ReportShareActions } from "@/components/ReportShareActions";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  AI_ADOPTION_TRUST_REPORT_SLUG,
  getAiAdoptionTrustImplications,
  getAiAdoptionTrustMetrics,
  getAiAdoptionTrustReportSources,
  getAiAdoptionTrustReportSummary,
  getAiAdoptionTrustVisualReports,
} from "@/lib/ai-adoption-trust-report";
import { BASE_URL } from "@/lib/site-url";
import { cn } from "@/lib/utils";

const REPORT_PATH = `/reports/${AI_ADOPTION_TRUST_REPORT_SLUG}`;
const REPORT_CARD_CLASS =
  "group relative h-full gap-0 overflow-hidden border-border/80 bg-card/60 py-0 shadow-sm transition-all hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-lg hover:shadow-primary/10";
const REPORT_CARD_GLOW_CLASS =
  "pointer-events-none absolute right-0 top-0 h-20 w-20 -translate-y-1/3 translate-x-1/3 rounded-full bg-primary/15 blur-2xl transition-opacity group-hover:opacity-100";
const OUTLINE_ACTION_CLASS =
  "inline-flex h-8 items-center justify-between gap-2 rounded-md border border-border/80 bg-background/80 px-3 text-sm font-medium text-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background";

function buildReportBriefMarkdown() {
  const summary = getAiAdoptionTrustReportSummary();
  const metrics = getAiAdoptionTrustMetrics();
  const implications = getAiAdoptionTrustImplications();
  const sources = getAiAdoptionTrustReportSources();
  const lines: string[] = [];
  lines.push(`# ${summary.title}`);
  lines.push("");
  lines.push(`Updated: ${new Date(summary.updatedAt).toLocaleDateString("en-US")}`);
  lines.push("");
  lines.push("## Core signals");
  metrics.forEach((metric) => {
    lines.push(`- ${metric.metric} — ${metric.detail}`);
  });
  lines.push("");
  lines.push("## Operational implications");
  implications.forEach((item) => lines.push(`- ${item}`));
  lines.push("");
  lines.push("## Sources");
  sources.forEach((source) => lines.push(`- ${source.label}: ${source.url}`));
  lines.push("");
  lines.push("Generated by The Stash reports.");
  return lines.join("\n");
}

function DatasetJsonLd() {
  const summary = getAiAdoptionTrustReportSummary();
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Dataset",
    name: summary.title,
    description: summary.description,
    url: `${BASE_URL}${REPORT_PATH}`,
    dateModified: summary.updatedAt,
    creator: {
      "@type": "Organization",
      name: "The Stash",
    },
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  );
}

export const metadata: Metadata = {
  title: "AI adoption and trust signals (2026) | The Stash",
  description:
    "Official-source report on AI coding adoption, trust gaps, and implementation implications for software teams.",
  alternates: { canonical: `${BASE_URL}${REPORT_PATH}` },
};

export default function AiAdoptionTrustSignalsPage() {
  const summary = getAiAdoptionTrustReportSummary();
  const metrics = getAiAdoptionTrustMetrics();
  const implications = getAiAdoptionTrustImplications();
  const sources = getAiAdoptionTrustReportSources();
  const visualReports = getAiAdoptionTrustVisualReports();
  const canonicalUrl = `${BASE_URL}${REPORT_PATH}`;
  const breadcrumbItems = [
    { name: "The Stash", url: `${BASE_URL}/` },
    { name: "Reports", url: `${BASE_URL}/reports` },
    { name: summary.title, url: canonicalUrl },
  ];
  const reportBrief = buildReportBriefMarkdown();

  return (
    <>
      <DatasetJsonLd />
      <BreadcrumbListJsonLd items={breadcrumbItems} />
      <div className="min-h-screen">
        <AppNav />
        <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
          <Breadcrumbs
            items={[
              { label: "The Stash", href: "/" },
              { label: "Reports", href: "/reports" },
              { label: summary.title },
            ]}
            className="mb-6"
          />

          <header className="space-y-4">
            <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
              Official-source signals
            </p>
            <h1 className="font-display text-3xl font-bold text-foreground sm:text-4xl">
              {summary.title}
            </h1>
            <p className="max-w-3xl text-lg leading-relaxed text-foreground">
              Snapshot of adoption velocity and trust risk for AI coding workflows, based on
              large-sample developer and platform reports.
            </p>
            <p className="text-sm text-muted-foreground">
              Updated {new Date(summary.updatedAt).toLocaleDateString()} ·
              {` ${summary.totalMetrics} signals`} · {summary.totalSources} sources
            </p>
            <ReportShareActions pageUrl={canonicalUrl} title={summary.title} briefMarkdown={reportBrief} />
          </header>

          <section className="mt-10 space-y-3" aria-labelledby="adoption-signals">
            <h2 id="adoption-signals" className="font-display text-xl font-semibold text-foreground">
              Key adoption and trust signals
            </h2>
            <ul className="space-y-4">
              {metrics.map((metric) => (
                <li key={metric.id}>
                  <Card className={REPORT_CARD_CLASS}>
                    <div className={REPORT_CARD_GLOW_CLASS} aria-hidden />
                    <CardHeader className="space-y-3 px-5 pt-5 pb-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge
                          variant="outline"
                          className="border-primary/25 bg-primary/[0.08] text-[0.65rem] font-semibold uppercase tracking-[0.12em] text-primary"
                        >
                          Signal
                        </Badge>
                        <p className="text-xs text-muted-foreground">{metric.sourceLabel}</p>
                      </div>
                      <CardTitle className="text-base leading-snug text-foreground">
                        {metric.metric}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="px-5 pt-3">
                      <p className="text-sm leading-relaxed text-muted-foreground">{metric.detail}</p>
                    </CardContent>
                    <CardFooter className="px-5 pt-4 pb-5">
                      <OutboundLink
                        href={metric.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                      >
                        Open source
                        <ArrowRightIcon className="size-4" aria-hidden />
                      </OutboundLink>
                    </CardFooter>
                  </Card>
                </li>
              ))}
            </ul>
          </section>

          {visualReports.length > 0 && (
            <section className="mt-10 space-y-4" aria-labelledby="adoption-visuals">
              <h2 id="adoption-visuals" className="font-display text-xl font-semibold text-foreground">
                Report visuals and infographics
              </h2>
              <div className="grid auto-rows-fr gap-4 md:grid-cols-2">
                {visualReports.map((report) => (
                  <Card key={report.id} className={REPORT_CARD_CLASS}>
                    <div className={REPORT_CARD_GLOW_CLASS} aria-hidden />
                    <div className="px-5 pt-5">
                      <div className="overflow-hidden rounded-xl border border-border/80">
                        <Image
                          src={report.imageUrl}
                          alt={report.imageAlt}
                          width={1200}
                          height={675}
                          className="h-auto w-full object-cover"
                          loading="lazy"
                        />
                      </div>
                    </div>
                    <CardHeader className="space-y-3 px-5 pt-4 pb-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge
                          variant="outline"
                          className="border-primary/25 bg-primary/[0.08] text-[0.65rem] font-semibold uppercase tracking-[0.12em] text-primary"
                        >
                          {report.organization}
                        </Badge>
                        <p className="text-xs text-muted-foreground">{report.publishedLabel}</p>
                      </div>
                      <CardTitle className="text-lg leading-snug text-foreground">
                        {report.title}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="flex flex-1 flex-col px-5 pt-3">
                      <p className="text-sm leading-relaxed text-muted-foreground">{report.summary}</p>
                      <ul className="mt-3 list-disc space-y-1.5 pl-5 text-sm text-muted-foreground">
                        {report.metrics.map((metric) => (
                          <li key={`${report.id}-${metric.value}-${metric.detail}`}>
                            <span className="font-semibold text-foreground">{metric.value}</span>{" "}
                            {metric.detail}
                          </li>
                        ))}
                      </ul>
                    </CardContent>
                    <CardFooter className="mt-auto flex flex-wrap gap-2 px-5 pt-4 pb-5">
                      <OutboundLink
                        href={report.reportUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                      >
                        Open report
                        <ArrowRightIcon className="size-4" aria-hidden />
                      </OutboundLink>
                      {report.downloadUrl && (
                        <OutboundLink
                          href={report.downloadUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                        >
                          Download source file
                          <ArrowRightIcon className="size-4" aria-hidden />
                        </OutboundLink>
                      )}
                    </CardFooter>
                  </Card>
                ))}
              </div>
            </section>
          )}

          <section className="mt-10 space-y-3" aria-labelledby="adoption-implications">
            <h2
              id="adoption-implications"
              className="font-display text-xl font-semibold text-foreground"
            >
              What this means for end users and buying teams
            </h2>
            <ul className="list-disc space-y-1.5 pl-5 text-sm text-muted-foreground">
              {implications.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
          </section>

          <BenchmarkReportSignup />

          <section className="mt-10 space-y-3" aria-labelledby="adoption-sources">
            <h2 id="adoption-sources" className="font-display text-xl font-semibold text-foreground">
              Sources
            </h2>
            <ul className="space-y-3 text-sm text-muted-foreground">
              {sources.map((source) => (
                <li key={source.url}>
                  <Card className="gap-0 border-border/80 bg-card/60 py-0">
                    <CardContent className="flex flex-wrap items-center justify-between gap-2 px-4 py-4">
                      <OutboundLink
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-foreground underline underline-offset-2 transition-colors hover:text-primary"
                      >
                        {source.label}
                      </OutboundLink>
                      <OutboundLink
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                      >
                        Open source
                        <ArrowRightIcon className="size-4" aria-hidden />
                      </OutboundLink>
                    </CardContent>
                  </Card>
                </li>
              ))}
            </ul>
          </section>
        </main>
      </div>
    </>
  );
}
