import Image from "next/image";
import type { Metadata } from "next";
import { ArrowRightIcon } from "@radix-ui/react-icons";
import { AppNav } from "@/components/AppNav";
import { BenchmarkReportSignup } from "@/components/BenchmarkReportSignup";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { BreadcrumbListJsonLd } from "@/components/BreadcrumbListJsonLd";
import { OutboundLink } from "@/components/OutboundLink";
import { ReportShareActions } from "@/components/ReportShareActions";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  AI_DISCOVERABILITY_REPORT_SLUG,
  getAiDiscoverabilityActions,
  getAiDiscoverabilityReportSummary,
  getAiDiscoverabilitySignals,
  getAiDiscoverabilitySources,
  getAiDiscoverabilityVisualSignals,
} from "@/lib/ai-discoverability-report";
import { BASE_URL } from "@/lib/site-url";
import { cn } from "@/lib/utils";

const REPORT_PATH = `/reports/${AI_DISCOVERABILITY_REPORT_SLUG}`;
const REPORT_CARD_CLASS =
  "group relative h-full gap-0 overflow-hidden border-border/80 bg-card/60 py-0 shadow-sm transition-all hover:-translate-y-0.5 hover:border-primary/35 hover:shadow-lg hover:shadow-primary/10";
const REPORT_CARD_GLOW_CLASS =
  "pointer-events-none absolute right-0 top-0 h-20 w-20 -translate-y-1/3 translate-x-1/3 rounded-full bg-primary/15 blur-2xl transition-opacity group-hover:opacity-100";
const OUTLINE_ACTION_CLASS =
  "inline-flex h-8 items-center justify-between gap-2 rounded-md border border-border/80 bg-background/80 px-3 text-sm font-medium text-foreground transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background";

function buildReportBriefMarkdown() {
  const summary = getAiDiscoverabilityReportSummary();
  const signals = getAiDiscoverabilitySignals();
  const actions = getAiDiscoverabilityActions();
  const sources = getAiDiscoverabilitySources();
  const lines: string[] = [];
  lines.push(`# ${summary.title}`);
  lines.push("");
  lines.push(`Updated: ${new Date(summary.updatedAt).toLocaleDateString("en-US")}`);
  lines.push("");
  lines.push("## Discoverability signals");
  signals.forEach((signal) => {
    lines.push(`- ${signal.signal} — ${signal.detail}`);
  });
  lines.push("");
  lines.push("## Execution actions");
  actions.forEach((action) => {
    lines.push(`- ${action.title}: ${action.executionPlan}`);
  });
  lines.push("");
  lines.push("## Sources");
  sources.forEach((source) => lines.push(`- ${source.label}: ${source.url}`));
  lines.push("");
  lines.push("Generated by The Stash reports.");
  return lines.join("\n");
}

function DatasetJsonLd() {
  const summary = getAiDiscoverabilityReportSummary();
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Report",
    name: summary.title,
    description: summary.description,
    url: `${BASE_URL}${REPORT_PATH}`,
    dateModified: summary.updatedAt,
    author: {
      "@type": "Organization",
      name: "The Stash",
    },
  };
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  );
}

export const metadata: Metadata = {
  title: "SEO and AI-answer discoverability signals (2026) | The Stash",
  description:
    "Official-source report translating Google AI search signals into concrete SEO and AI-answer discoverability actions.",
  alternates: { canonical: `${BASE_URL}${REPORT_PATH}` },
};

export default function SeoAiAnswerDiscoverabilityPage() {
  const summary = getAiDiscoverabilityReportSummary();
  const signals = getAiDiscoverabilitySignals();
  const actions = getAiDiscoverabilityActions();
  const visuals = getAiDiscoverabilityVisualSignals();
  const sources = getAiDiscoverabilitySources();
  const canonicalUrl = `${BASE_URL}${REPORT_PATH}`;
  const breadcrumbItems = [
    { name: "The Stash", url: `${BASE_URL}/` },
    { name: "Reports", url: `${BASE_URL}/reports` },
    { name: summary.title, url: canonicalUrl },
  ];
  const reportBrief = buildReportBriefMarkdown();

  return (
    <>
      <DatasetJsonLd />
      <BreadcrumbListJsonLd items={breadcrumbItems} />
      <div className="min-h-screen">
        <AppNav />
        <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8">
          <Breadcrumbs
            items={[
              { label: "The Stash", href: "/" },
              { label: "Reports", href: "/reports" },
              { label: summary.title },
            ]}
            className="mb-6"
          />

          <header className="space-y-4">
            <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
              Discoverability research
            </p>
            <h1 className="font-display text-3xl font-bold text-foreground sm:text-4xl">
              {summary.title}
            </h1>
            <p className="max-w-3xl text-lg leading-relaxed text-foreground">
              Official AI-search adoption signals translated into practical execution steps for
              ranking visibility, AI answer citations, and backlink-worthy report publishing.
            </p>
            <p className="text-sm text-muted-foreground">
              Updated {new Date(summary.updatedAt).toLocaleDateString()} ·
              {` ${summary.totalSignals} signals`} · {summary.totalSources} sources
            </p>
            <ReportShareActions pageUrl={canonicalUrl} title={summary.title} briefMarkdown={reportBrief} />
          </header>

          <section className="mt-10 space-y-3" aria-labelledby="discoverability-signals">
            <h2
              id="discoverability-signals"
              className="font-display text-xl font-semibold text-foreground"
            >
              Signals that changed the SEO + AI answer landscape
            </h2>
            <ul className="space-y-4">
              {signals.map((signal) => (
                <li key={signal.id}>
                  <Card className={REPORT_CARD_CLASS}>
                    <div className={REPORT_CARD_GLOW_CLASS} aria-hidden />
                    <CardHeader className="space-y-3 px-5 pt-5 pb-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge
                          variant="outline"
                          className="border-primary/25 bg-primary/[0.08] text-[0.65rem] font-semibold uppercase tracking-[0.12em] text-primary"
                        >
                          Signal
                        </Badge>
                        <p className="text-xs text-muted-foreground">
                          {new Date(signal.sourcePublishedAt).toLocaleDateString()}
                        </p>
                      </div>
                      <CardTitle className="text-base leading-snug text-foreground">
                        {signal.signal}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="px-5 pt-3">
                      <p className="text-sm leading-relaxed text-muted-foreground">{signal.detail}</p>
                    </CardContent>
                    <CardFooter className="flex flex-wrap items-center gap-2 px-5 pt-4 pb-5">
                      <span className="text-xs text-muted-foreground">{signal.sourceLabel}</span>
                      <OutboundLink
                        href={signal.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                      >
                        Open source
                        <ArrowRightIcon className="size-4" aria-hidden />
                      </OutboundLink>
                    </CardFooter>
                  </Card>
                </li>
              ))}
            </ul>
          </section>

          {visuals.length > 0 && (
            <section className="mt-10 space-y-4" aria-labelledby="discoverability-visuals">
              <h2
                id="discoverability-visuals"
                className="font-display text-xl font-semibold text-foreground"
              >
                Official visuals and infographics
              </h2>
              <div className="grid auto-rows-fr gap-4 md:grid-cols-2">
                {visuals.map((signal) => (
                  <Card key={signal.id} className={REPORT_CARD_CLASS}>
                    <div className={REPORT_CARD_GLOW_CLASS} aria-hidden />
                    <div className="px-5 pt-5">
                      <div className="overflow-hidden rounded-xl border border-border/80">
                        <Image
                          src={signal.imageUrl}
                          alt={signal.imageAlt}
                          width={1200}
                          height={675}
                          className="h-auto w-full object-cover"
                          loading="lazy"
                        />
                      </div>
                    </div>
                    <CardHeader className="space-y-3 px-5 pt-4 pb-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge
                          variant="outline"
                          className="border-primary/25 bg-primary/[0.08] text-[0.65rem] font-semibold uppercase tracking-[0.12em] text-primary"
                        >
                          Visual source
                        </Badge>
                        <p className="text-xs text-muted-foreground">
                          {new Date(signal.sourcePublishedAt).toLocaleDateString()}
                        </p>
                      </div>
                      <CardTitle className="text-base leading-snug text-foreground">
                        {signal.signal}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="flex-1 px-5 pt-3">
                      <p className="text-sm leading-relaxed text-muted-foreground">
                        {signal.sourceLabel}
                      </p>
                    </CardContent>
                    <CardFooter className="mt-auto px-5 pt-4 pb-5">
                      <OutboundLink
                        href={signal.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                      >
                        Open source
                        <ArrowRightIcon className="size-4" aria-hidden />
                      </OutboundLink>
                    </CardFooter>
                  </Card>
                ))}
              </div>
            </section>
          )}

          <section className="mt-10 space-y-3" aria-labelledby="discoverability-actions">
            <h2
              id="discoverability-actions"
              className="font-display text-xl font-semibold text-foreground"
            >
              Execution framework for discoverability
            </h2>
            <div className="overflow-x-auto rounded-xl border border-border">
              <table className="w-full min-w-[860px] text-sm">
                <thead className="bg-muted/40">
                  <tr>
                    <th className="px-3 py-2 text-left font-medium">Action</th>
                    <th className="px-3 py-2 text-left font-medium">Why this matters</th>
                    <th className="px-3 py-2 text-left font-medium">How to execute</th>
                  </tr>
                </thead>
                <tbody>
                  {actions.map((action) => (
                    <tr key={action.id} className="border-t border-border align-top">
                      <td className="px-3 py-2 font-medium text-foreground">{action.title}</td>
                      <td className="px-3 py-2 text-muted-foreground">{action.whyItMatters}</td>
                      <td className="px-3 py-2 text-muted-foreground">{action.executionPlan}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <BenchmarkReportSignup />

          <section className="mt-10 space-y-3" aria-labelledby="discoverability-sources">
            <h2
              id="discoverability-sources"
              className="font-display text-xl font-semibold text-foreground"
            >
              Sources
            </h2>
            <ul className="space-y-3 text-sm text-muted-foreground">
              {sources.map((source) => (
                <li key={source.url}>
                  <Card className="gap-0 border-border/80 bg-card/60 py-0">
                    <CardContent className="flex flex-wrap items-center justify-between gap-2 px-4 py-4">
                      <OutboundLink
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-foreground underline underline-offset-2 transition-colors hover:text-primary"
                      >
                        {source.label}
                      </OutboundLink>
                      <OutboundLink
                        href={source.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className={cn(OUTLINE_ACTION_CLASS, "w-fit justify-between")}
                      >
                        Open source
                        <ArrowRightIcon className="size-4" aria-hidden />
                      </OutboundLink>
                    </CardContent>
                  </Card>
                </li>
              ))}
            </ul>
          </section>
        </main>
      </div>
    </>
  );
}
