#!/usr/bin/env node
/**
 * Build an env file for Vercel (Google Search Console / Indexing API).
 * Usage: node scripts/write-gsc-env.mjs /path/to/service-account.json
 *
 * Writes env.gsc.vercel with GOOGLE_APPLICATION_CREDENTIALS_JSON and a generated
 * GSC_WEBHOOK_SECRET. Import that file in Vercel (Settings → Environment Variables → Import .env)
 * or copy the values manually. Do not commit env.gsc.vercel (it is gitignored).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";

const jsonPath = process.argv[2];
if (!jsonPath) {
  console.error("Usage: node scripts/write-gsc-env.mjs /path/to/service-account.json");
  process.exit(1);
}

let jsonStr;
try {
  jsonStr = readFileSync(jsonPath, "utf8");
} catch (e) {
  console.error("Could not read file:", jsonPath, e.message);
  process.exit(1);
}

// Minify to one line so it's safe as an env value
const minified = JSON.stringify(JSON.parse(jsonStr));
const secret = randomBytes(32).toString("hex");

const lines = [
  "# Generated by scripts/write-gsc-env.mjs — do not commit",
  "GOOGLE_APPLICATION_CREDENTIALS_JSON=" + minified,
  "GSC_WEBHOOK_SECRET=" + secret,
  "# GSC_SITE_URL=https://www.thestash.xyz/",
];

const outPath = "env.gsc.vercel";
writeFileSync(outPath, lines.join("\n") + "\n", "utf8");
console.log("Wrote " + outPath);
console.log("GSC_WEBHOOK_SECRET (save this): " + secret);
console.log("In Vercel: Settings → Environment Variables → Import .env → choose " + outPath);
